excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://krevony.github.io
name: KYLOG
description: 장인정신을 가진 디자이너, 열정있는 프로그래머.<br />감성적 프로그래머, 이성적 디자이너.
author: Kyle Lee
avatar: http://www.gravatar.com/avatar/8776ebb9011c7f999007b947e6565f43?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 